local slA = 0
local slB = 0
local slC = 0
local hgt = 0
local varA = 0
local varB = 0
local vol = 0
print("Volume Calculator")
print("========================")
print("1: Triangular Prism")
print("2: Rectangular Prism")
print("3: Pentagonal Prism")
print("4: Hexagonal Prism")
print("5: Cylinder")
print("6: Triangular Pyramid")
print("7: Pyramid")
print("8: Pentagonal Pyramid")
print("9: Hexagonal Pyramid")
print("10: Sphere")
print("11: Hemisphere")
print("12: Cone")
io.write("Choice: ")
objSelect = io.read()
print("========================")
if objSelect == "1" then
	io.write("Base height: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Base edge length: ")
	slB = io.read()
	slB = tonumber(slB)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
  print("========================")
	vol = ((1/2)*slA*slB*hgt)
	print("The volume of a Triangular Prism with:\nBase height = ".. slA .."\nBase length = ".. slB .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "2" then
	io.write("Side length A: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Side length B: ")
	slB = io.read()
	slB = tonumber(slB)
	io.write("Side length C: ")
	slC = io.read()
	slC = tonumber(slC)
  print("========================")
	vol = (slA * slB * slC)
	print("The volume of a Rectangular Prism with:\nSide length A = ".. slA .."\nSide length B = ".. slB .."\nSide length C = ".. slC .."\nequals: ".. vol .." cube units")
elseif objSelect == "3" then
	io.write("Base edge length: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
  print("========================")
  vol = (math.sqrt(25 + 10 * math.sqrt(5)) * (slA * slA) * hgt)/4
  print("The volume of a Pentagonal Prism with:\nEdge length = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "4" then
	io.write("Base edge length: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = ((3*math.sqrt(3))/2)*((slA*slA)*hgt)
	print("The volume of a Hexagonal Prism with:\nEdge length = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "5" then
	io.write("Radius: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = math.pi*((slA*slA)*hgt)
	print("The volume of a Cylinder with:\nRadius = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "6" then
	io.write("Area of triangle base: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = 1/3*(slA*hgt)
	print("The volume of a Triangular Pyramid with:\nBase area = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units (MAY BE WRONG)")
elseif objSelect == "7" then
	io.write("Base length: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Base width: ")
	slB = io.read()
	slB = tonumber(slB)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = (slA*slB*hgt)/3
	print("The volume of a Pyramid with:\nBase length = ".. slA .."\nBase width = ".. slB .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "8" then
	io.write("Base edge length: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = (1/12)*(slA*slA)*hgt*math.sqrt(25+10*math.sqrt(5))
	print("The volume of a Pentagonal Pyramid with:\nBase edge length = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "9" then
	io.write("Base edge length: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = (math.sqrt(3)/2)*(slA*slA)*hgt
	print("The volume of a Hexagonal Pyramid with:\nBase edge length = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
elseif objSelect == "10" then
	io.write("Radius: ")
	slA = io.read()
	slA = tonumber(slA)
	vol = (4/3)*math.pi*(slA*slA*slA)
	print("The volume of a Sphere with:\nRadius = ".. slA .."\nequals: ".. vol .." cube units")
elseif objSelect == "11" then
	io.write("Radius: ")
	slA = io.read()
	slA = tonumber(slA)
	vol = ((4/3)*math.pi*(slA*slA*slA))/2
	print("The volume of a Hemisphere with:\nRadius = ".. slA .."\nequals: ".. vol .." cube units")
elseif objSelect == "12" then
	io.write("Radius: ")
	slA = io.read()
	slA = tonumber(slA)
	io.write("Height: ")
	hgt = io.read()
	hgt = tonumber(hgt)
	vol = math.pi*(slA*slA)*(hgt/3)
	print("The volume of a Cone with:\nRadius = ".. slA .."\nHeight = ".. hgt .."\nequals: ".. vol .." cube units")
end
print("========================")
io.write("Press enter to close this window...")
io.read()
